import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'de' | 'ru' | 'es' | 'zh' | 'pt-br';

export interface LanguageConfig {
  code: Language;
  name: string;
  flag: string;
}

export const languages: LanguageConfig[] = [
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'pt-br', name: 'Português (BR)', flag: '🇧🇷' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translateText: (text: string, targetLang?: Language) => Promise<string>;
  isTranslating: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// UI translations for each language
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.back': 'Retour',
    'nav.backToSubjects': 'Retour aux matières',
    'nav.backToStories': 'Retour aux histoires',
    'nav.quitStory': "Quitter l'histoire",
    'nav.home': 'Accueil',
    
    // Auth
    'auth.login': 'Connexion',
    'auth.logout': 'Se déconnecter',
    'auth.register': 'Créer un compte',
    'auth.noAccount': 'Pas encore de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.firstName': 'Prénom',
    'auth.loginTitle': 'Connexion',
    'auth.registerTitle': 'Créer un compte',
    'auth.loginSubtitle': 'Retrouve tes histoires et ta progression !',
    'auth.registerSubtitle': 'Rejoins les héros de la classe !',
    'auth.loginSuccess': 'Connexion réussie !',
    'auth.welcomeBack': 'Content de te revoir !',
    'auth.loginError': 'Erreur de connexion',
    'auth.invalidCredentials': 'Email ou mot de passe incorrect.',
    'auth.error': 'Erreur',
    'auth.genericError': 'Une erreur est survenue. Réessayez plus tard.',
    'auth.submit': 'Se connecter',
    'auth.createAccount': 'Créer mon compte',
    
    // User Menu
    'menu.myAccount': 'Mon compte',
    'menu.changeAvatar': "Changer d'avatar",
    'menu.myStories': 'Mes histoires',
    'menu.admin': 'Administration',
    'menu.seeYou': 'À bientôt !',
    'menu.loggedOut': 'Tu as été déconnecté.',
    'menu.adventurer': 'Aventurier',
    
    // Avatar Dialog
    'avatar.chooseTitle': 'Choisis ton avatar',
    'avatar.chooseSubtitle': 'Sélectionne le personnage qui te ressemble !',
    'avatar.cancel': 'Annuler',
    'avatar.save': 'Enregistrer',
    'avatar.saving': 'Enregistrement...',
    'avatar.changed': 'Avatar modifié !',
    'avatar.changedDesc': 'Ton nouvel avatar est super !',
    'avatar.error': "Impossible de changer l'avatar",
    
    // Stories Dashboard
    'stories.chooseAdventure': 'Choisis ton aventure !',
    'stories.saveProgress': 'Enregistrer ma progression',
    'stories.loading': 'Chargement des histoires...',
    'stories.noStories': 'Aucune histoire disponible pour cette matière en',
    'stories.chooseOther': 'Choisir une autre matière',
    
    // Story Reader
    'story.pageNotFound': 'Page introuvable',
    'story.pageNotFoundDesc': "Cette page n'existe pas.",
    'story.backToStories': 'Retour aux histoires',
    'story.endingHappy': "Fin de l'histoire !",
    'story.endingAlt': 'Une autre fin...',
    'story.listenStory': "Écouter l'histoire",
    'story.stopListening': 'Arrêter',
    'story.downloadColoring': 'Coloriage dinosaures',
    'story.whatToDo': 'Que veux-tu faire ?',
    'story.restart': 'Recommencer cette histoire',
    'story.otherStories': 'Autres histoires',
    
    // Story Start
    'start.enterName': 'Entre ton prénom',
    'start.yourName': 'Ton prénom',
    'start.namePlaceholder': 'Ex: Emma, Lucas...',
    'start.nameHint': 'Ton prénom apparaîtra dans l\'histoire !',
    'start.chooseGender': 'Choisis ton genre',
    'start.genderMasculine': 'Masculin',
    'start.genderFeminine': 'Féminin',
    'start.genderNeutral': 'Neutre',
    'start.genderHint': 'Cela adaptera certains mots de l\'histoire.',
    'start.beginAdventure': "C'est parti pour l'aventure !",
    'start.back': 'Retour',
    
    // Footer
    'footer.tagline': 'Des histoires magiques pour apprendre en s\'amusant',
    'footer.rights': 'Tous droits réservés.',
    
    // Grades
    'grades.title': 'À quel niveau es-tu ?',
    'grades.subtitle': 'Choisis ta classe pour découvrir des aventures adaptées !',
    
    // General
    'general.loading': 'Chargement...',
    'general.error': 'Erreur',
    'general.success': 'Succès',
    'general.cancel': 'Annuler',
    'general.save': 'Enregistrer',
    'general.delete': 'Supprimer',
    'general.edit': 'Modifier',
    'general.close': 'Fermer',
  },
  en: {
    // Navigation
    'nav.back': 'Back',
    'nav.backToSubjects': 'Back to subjects',
    'nav.backToStories': 'Back to stories',
    'nav.quitStory': 'Quit story',
    'nav.home': 'Home',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Log out',
    'auth.register': 'Create account',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.firstName': 'First name',
    'auth.loginTitle': 'Login',
    'auth.registerTitle': 'Create account',
    'auth.loginSubtitle': 'Find your stories and progress!',
    'auth.registerSubtitle': 'Join the class heroes!',
    'auth.loginSuccess': 'Login successful!',
    'auth.welcomeBack': 'Welcome back!',
    'auth.loginError': 'Login error',
    'auth.invalidCredentials': 'Invalid email or password.',
    'auth.error': 'Error',
    'auth.genericError': 'An error occurred. Try again later.',
    'auth.submit': 'Log in',
    'auth.createAccount': 'Create my account',
    
    // User Menu
    'menu.myAccount': 'My account',
    'menu.changeAvatar': 'Change avatar',
    'menu.myStories': 'My stories',
    'menu.admin': 'Administration',
    'menu.seeYou': 'See you soon!',
    'menu.loggedOut': 'You have been logged out.',
    'menu.adventurer': 'Adventurer',
    
    // Avatar Dialog
    'avatar.chooseTitle': 'Choose your avatar',
    'avatar.chooseSubtitle': 'Select the character that looks like you!',
    'avatar.cancel': 'Cancel',
    'avatar.save': 'Save',
    'avatar.saving': 'Saving...',
    'avatar.changed': 'Avatar changed!',
    'avatar.changedDesc': 'Your new avatar looks great!',
    'avatar.error': 'Unable to change avatar',
    
    // Stories Dashboard
    'stories.chooseAdventure': 'Choose your adventure!',
    'stories.saveProgress': 'Save my progress',
    'stories.loading': 'Loading stories...',
    'stories.noStories': 'No stories available for this subject in',
    'stories.chooseOther': 'Choose another subject',
    
    // Story Reader
    'story.pageNotFound': 'Page not found',
    'story.pageNotFoundDesc': 'This page does not exist.',
    'story.backToStories': 'Back to stories',
    'story.endingHappy': 'The End!',
    'story.endingAlt': 'Another ending...',
    'story.listenStory': 'Listen to the story',
    'story.stopListening': 'Stop',
    'story.downloadColoring': 'Dinosaur coloring',
    'story.whatToDo': 'What do you want to do?',
    'story.restart': 'Restart this story',
    'story.otherStories': 'Other stories',
    
    // Story Start
    'start.enterName': 'Enter your name',
    'start.yourName': 'Your name',
    'start.namePlaceholder': 'E.g: Emma, Lucas...',
    'start.nameHint': 'Your name will appear in the story!',
    'start.chooseGender': 'Choose your gender',
    'start.genderMasculine': 'Masculine',
    'start.genderFeminine': 'Feminine',
    'start.genderNeutral': 'Neutral',
    'start.genderHint': 'This will adapt some words in the story.',
    'start.beginAdventure': "Let's start the adventure!",
    'start.back': 'Back',
    
    // Footer
    'footer.tagline': 'Magical stories to learn while having fun',
    'footer.rights': 'All rights reserved.',
    
    // Grades
    'grades.title': 'What grade are you in?',
    'grades.subtitle': 'Choose your class to discover tailored adventures!',
    
    // General
    'general.loading': 'Loading...',
    'general.error': 'Error',
    'general.success': 'Success',
    'general.cancel': 'Cancel',
    'general.save': 'Save',
    'general.delete': 'Delete',
    'general.edit': 'Edit',
    'general.close': 'Close',
  },
  de: {
    'nav.back': 'Zurück',
    'nav.backToSubjects': 'Zurück zu den Fächern',
    'nav.backToStories': 'Zurück zu den Geschichten',
    'nav.quitStory': 'Geschichte beenden',
    'nav.home': 'Startseite',
    'auth.login': 'Anmelden',
    'auth.logout': 'Abmelden',
    'auth.register': 'Konto erstellen',
    'auth.noAccount': 'Noch kein Konto?',
    'auth.hasAccount': 'Bereits ein Konto?',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.firstName': 'Vorname',
    'auth.loginTitle': 'Anmelden',
    'auth.registerTitle': 'Konto erstellen',
    'auth.loginSubtitle': 'Finde deine Geschichten und deinen Fortschritt!',
    'auth.registerSubtitle': 'Werde ein Klassenheld!',
    'auth.loginSuccess': 'Erfolgreich angemeldet!',
    'auth.welcomeBack': 'Willkommen zurück!',
    'auth.loginError': 'Anmeldefehler',
    'auth.invalidCredentials': 'Ungültige E-Mail oder Passwort.',
    'auth.error': 'Fehler',
    'auth.genericError': 'Ein Fehler ist aufgetreten. Versuche es später erneut.',
    'auth.submit': 'Anmelden',
    'auth.createAccount': 'Mein Konto erstellen',
    'menu.myAccount': 'Mein Konto',
    'menu.changeAvatar': 'Avatar ändern',
    'menu.myStories': 'Meine Geschichten',
    'menu.admin': 'Administration',
    'menu.seeYou': 'Bis bald!',
    'menu.loggedOut': 'Du wurdest abgemeldet.',
    'menu.adventurer': 'Abenteurer',
    'avatar.chooseTitle': 'Wähle deinen Avatar',
    'avatar.chooseSubtitle': 'Wähle die Figur, die dir ähnelt!',
    'avatar.cancel': 'Abbrechen',
    'avatar.save': 'Speichern',
    'avatar.saving': 'Speichern...',
    'avatar.changed': 'Avatar geändert!',
    'avatar.changedDesc': 'Dein neuer Avatar sieht toll aus!',
    'avatar.error': 'Avatar konnte nicht geändert werden',
    'stories.chooseAdventure': 'Wähle dein Abenteuer!',
    'stories.saveProgress': 'Meinen Fortschritt speichern',
    'stories.loading': 'Geschichten werden geladen...',
    'stories.noStories': 'Keine Geschichten für dieses Fach in',
    'stories.chooseOther': 'Ein anderes Fach wählen',
    'story.pageNotFound': 'Seite nicht gefunden',
    'story.pageNotFoundDesc': 'Diese Seite existiert nicht.',
    'story.backToStories': 'Zurück zu den Geschichten',
    'story.endingHappy': 'Ende der Geschichte!',
    'story.endingAlt': 'Ein anderes Ende...',
    'story.listenStory': 'Geschichte anhören',
    'story.stopListening': 'Stoppen',
    'story.downloadColoring': 'Dinosaurier-Ausmalbild',
    'story.whatToDo': 'Was möchtest du tun?',
    'story.restart': 'Diese Geschichte neu starten',
    'story.otherStories': 'Andere Geschichten',
    'start.enterName': 'Gib deinen Namen ein',
    'start.yourName': 'Dein Name',
    'start.namePlaceholder': 'Z.B: Emma, Lucas...',
    'start.nameHint': 'Dein Name erscheint in der Geschichte!',
    'start.chooseGender': 'Wähle dein Geschlecht',
    'start.genderMasculine': 'Männlich',
    'start.genderFeminine': 'Weiblich',
    'start.genderNeutral': 'Neutral',
    'start.genderHint': 'Dies passt einige Wörter in der Geschichte an.',
    'start.beginAdventure': 'Auf ins Abenteuer!',
    'start.back': 'Zurück',
    'footer.tagline': 'Magische Geschichten zum spielerischen Lernen',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'grades.title': 'In welcher Klasse bist du?',
    'grades.subtitle': 'Wähle deine Klasse für passende Abenteuer!',
    'general.loading': 'Laden...',
    'general.error': 'Fehler',
    'general.success': 'Erfolg',
    'general.cancel': 'Abbrechen',
    'general.save': 'Speichern',
    'general.delete': 'Löschen',
    'general.edit': 'Bearbeiten',
    'general.close': 'Schließen',
  },
  ru: {
    'nav.back': 'Назад',
    'nav.backToSubjects': 'Вернуться к предметам',
    'nav.backToStories': 'Вернуться к историям',
    'nav.quitStory': 'Выйти из истории',
    'nav.home': 'Главная',
    'auth.login': 'Войти',
    'auth.logout': 'Выйти',
    'auth.register': 'Создать аккаунт',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.hasAccount': 'Уже есть аккаунт?',
    'auth.email': 'Электронная почта',
    'auth.password': 'Пароль',
    'auth.firstName': 'Имя',
    'auth.loginTitle': 'Вход',
    'auth.registerTitle': 'Создать аккаунт',
    'auth.loginSubtitle': 'Найди свои истории и прогресс!',
    'auth.registerSubtitle': 'Присоединяйся к героям класса!',
    'auth.loginSuccess': 'Вход выполнен!',
    'auth.welcomeBack': 'С возвращением!',
    'auth.loginError': 'Ошибка входа',
    'auth.invalidCredentials': 'Неверный email или пароль.',
    'auth.error': 'Ошибка',
    'auth.genericError': 'Произошла ошибка. Попробуйте позже.',
    'auth.submit': 'Войти',
    'auth.createAccount': 'Создать аккаунт',
    'menu.myAccount': 'Мой аккаунт',
    'menu.changeAvatar': 'Изменить аватар',
    'menu.myStories': 'Мои истории',
    'menu.admin': 'Администрация',
    'menu.seeYou': 'До скорой встречи!',
    'menu.loggedOut': 'Вы вышли из системы.',
    'menu.adventurer': 'Искатель приключений',
    'avatar.chooseTitle': 'Выбери свой аватар',
    'avatar.chooseSubtitle': 'Выбери персонажа, который похож на тебя!',
    'avatar.cancel': 'Отмена',
    'avatar.save': 'Сохранить',
    'avatar.saving': 'Сохранение...',
    'avatar.changed': 'Аватар изменён!',
    'avatar.changedDesc': 'Твой новый аватар отлично выглядит!',
    'avatar.error': 'Не удалось изменить аватар',
    'stories.chooseAdventure': 'Выбери своё приключение!',
    'stories.saveProgress': 'Сохранить прогресс',
    'stories.loading': 'Загрузка историй...',
    'stories.noStories': 'Нет историй для этого предмета в',
    'stories.chooseOther': 'Выбрать другой предмет',
    'story.pageNotFound': 'Страница не найдена',
    'story.pageNotFoundDesc': 'Эта страница не существует.',
    'story.backToStories': 'Вернуться к историям',
    'story.endingHappy': 'Конец истории!',
    'story.endingAlt': 'Другой конец...',
    'story.listenStory': 'Слушать историю',
    'story.stopListening': 'Остановить',
    'story.downloadColoring': 'Раскраска с динозаврами',
    'story.whatToDo': 'Что ты хочешь сделать?',
    'story.restart': 'Начать историю сначала',
    'story.otherStories': 'Другие истории',
    'start.enterName': 'Введи своё имя',
    'start.yourName': 'Твоё имя',
    'start.namePlaceholder': 'Напр: Эмма, Лукас...',
    'start.nameHint': 'Твоё имя появится в истории!',
    'start.chooseGender': 'Выбери пол',
    'start.genderMasculine': 'Мужской',
    'start.genderFeminine': 'Женский',
    'start.genderNeutral': 'Нейтральный',
    'start.genderHint': 'Это адаптирует некоторые слова в истории.',
    'start.beginAdventure': 'Начинаем приключение!',
    'start.back': 'Назад',
    'footer.tagline': 'Волшебные истории для весёлого обучения',
    'footer.rights': 'Все права защищены.',
    'grades.title': 'В каком ты классе?',
    'grades.subtitle': 'Выбери класс для подходящих приключений!',
    'general.loading': 'Загрузка...',
    'general.error': 'Ошибка',
    'general.success': 'Успех',
    'general.cancel': 'Отмена',
    'general.save': 'Сохранить',
    'general.delete': 'Удалить',
    'general.edit': 'Редактировать',
    'general.close': 'Закрыть',
  },
  es: {
    'nav.back': 'Volver',
    'nav.backToSubjects': 'Volver a las materias',
    'nav.backToStories': 'Volver a las historias',
    'nav.quitStory': 'Salir de la historia',
    'nav.home': 'Inicio',
    'auth.login': 'Iniciar sesión',
    'auth.logout': 'Cerrar sesión',
    'auth.register': 'Crear cuenta',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.firstName': 'Nombre',
    'auth.loginTitle': 'Iniciar sesión',
    'auth.registerTitle': 'Crear cuenta',
    'auth.loginSubtitle': '¡Encuentra tus historias y tu progreso!',
    'auth.registerSubtitle': '¡Únete a los héroes de la clase!',
    'auth.loginSuccess': '¡Inicio de sesión exitoso!',
    'auth.welcomeBack': '¡Bienvenido de nuevo!',
    'auth.loginError': 'Error de inicio de sesión',
    'auth.invalidCredentials': 'Correo o contraseña incorrectos.',
    'auth.error': 'Error',
    'auth.genericError': 'Ocurrió un error. Inténtalo más tarde.',
    'auth.submit': 'Iniciar sesión',
    'auth.createAccount': 'Crear mi cuenta',
    'menu.myAccount': 'Mi cuenta',
    'menu.changeAvatar': 'Cambiar avatar',
    'menu.myStories': 'Mis historias',
    'menu.admin': 'Administración',
    'menu.seeYou': '¡Hasta pronto!',
    'menu.loggedOut': 'Has cerrado sesión.',
    'menu.adventurer': 'Aventurero',
    'avatar.chooseTitle': 'Elige tu avatar',
    'avatar.chooseSubtitle': '¡Selecciona el personaje que se parezca a ti!',
    'avatar.cancel': 'Cancelar',
    'avatar.save': 'Guardar',
    'avatar.saving': 'Guardando...',
    'avatar.changed': '¡Avatar cambiado!',
    'avatar.changedDesc': '¡Tu nuevo avatar se ve genial!',
    'avatar.error': 'No se pudo cambiar el avatar',
    'stories.chooseAdventure': '¡Elige tu aventura!',
    'stories.saveProgress': 'Guardar mi progreso',
    'stories.loading': 'Cargando historias...',
    'stories.noStories': 'No hay historias disponibles para esta materia en',
    'stories.chooseOther': 'Elegir otra materia',
    'story.pageNotFound': 'Página no encontrada',
    'story.pageNotFoundDesc': 'Esta página no existe.',
    'story.backToStories': 'Volver a las historias',
    'story.endingHappy': '¡Fin de la historia!',
    'story.endingAlt': 'Otro final...',
    'story.listenStory': 'Escuchar la historia',
    'story.stopListening': 'Detener',
    'story.downloadColoring': 'Colorear dinosaurios',
    'story.whatToDo': '¿Qué quieres hacer?',
    'story.restart': 'Reiniciar esta historia',
    'story.otherStories': 'Otras historias',
    'start.enterName': 'Ingresa tu nombre',
    'start.yourName': 'Tu nombre',
    'start.namePlaceholder': 'Ej: Emma, Lucas...',
    'start.nameHint': '¡Tu nombre aparecerá en la historia!',
    'start.chooseGender': 'Elige tu género',
    'start.genderMasculine': 'Masculino',
    'start.genderFeminine': 'Femenino',
    'start.genderNeutral': 'Neutral',
    'start.genderHint': 'Esto adaptará algunas palabras de la historia.',
    'start.beginAdventure': '¡Comienza la aventura!',
    'start.back': 'Volver',
    'footer.tagline': 'Historias mágicas para aprender jugando',
    'footer.rights': 'Todos los derechos reservados.',
    'grades.title': '¿En qué grado estás?',
    'grades.subtitle': '¡Elige tu clase para descubrir aventuras adaptadas!',
    'general.loading': 'Cargando...',
    'general.error': 'Error',
    'general.success': 'Éxito',
    'general.cancel': 'Cancelar',
    'general.save': 'Guardar',
    'general.delete': 'Eliminar',
    'general.edit': 'Editar',
    'general.close': 'Cerrar',
  },
  zh: {
    'nav.back': '返回',
    'nav.backToSubjects': '返回科目',
    'nav.backToStories': '返回故事',
    'nav.quitStory': '退出故事',
    'nav.home': '首页',
    'auth.login': '登录',
    'auth.logout': '退出登录',
    'auth.register': '创建账户',
    'auth.noAccount': '还没有账户？',
    'auth.hasAccount': '已有账户？',
    'auth.email': '电子邮箱',
    'auth.password': '密码',
    'auth.firstName': '名字',
    'auth.loginTitle': '登录',
    'auth.registerTitle': '创建账户',
    'auth.loginSubtitle': '找回你的故事和进度！',
    'auth.registerSubtitle': '加入班级英雄！',
    'auth.loginSuccess': '登录成功！',
    'auth.welcomeBack': '欢迎回来！',
    'auth.loginError': '登录错误',
    'auth.invalidCredentials': '邮箱或密码错误。',
    'auth.error': '错误',
    'auth.genericError': '发生错误，请稍后重试。',
    'auth.submit': '登录',
    'auth.createAccount': '创建账户',
    'menu.myAccount': '我的账户',
    'menu.changeAvatar': '更换头像',
    'menu.myStories': '我的故事',
    'menu.admin': '管理',
    'menu.seeYou': '再见！',
    'menu.loggedOut': '您已退出登录。',
    'menu.adventurer': '冒险家',
    'avatar.chooseTitle': '选择你的头像',
    'avatar.chooseSubtitle': '选择像你的角色！',
    'avatar.cancel': '取消',
    'avatar.save': '保存',
    'avatar.saving': '保存中...',
    'avatar.changed': '头像已更改！',
    'avatar.changedDesc': '你的新头像看起来很棒！',
    'avatar.error': '无法更改头像',
    'stories.chooseAdventure': '选择你的冒险！',
    'stories.saveProgress': '保存进度',
    'stories.loading': '加载故事中...',
    'stories.noStories': '该科目没有可用的故事',
    'stories.chooseOther': '选择其他科目',
    'story.pageNotFound': '页面未找到',
    'story.pageNotFoundDesc': '此页面不存在。',
    'story.backToStories': '返回故事',
    'story.endingHappy': '故事结束！',
    'story.endingAlt': '另一个结局...',
    'story.listenStory': '听故事',
    'story.stopListening': '停止',
    'story.downloadColoring': '恐龙涂色',
    'story.whatToDo': '你想做什么？',
    'story.restart': '重新开始这个故事',
    'story.otherStories': '其他故事',
    'start.enterName': '输入你的名字',
    'start.yourName': '你的名字',
    'start.namePlaceholder': '例如：艾玛、卢卡斯...',
    'start.nameHint': '你的名字会出现在故事中！',
    'start.chooseGender': '选择你的性别',
    'start.genderMasculine': '男性',
    'start.genderFeminine': '女性',
    'start.genderNeutral': '中性',
    'start.genderHint': '这将调整故事中的某些词语。',
    'start.beginAdventure': '开始冒险吧！',
    'start.back': '返回',
    'footer.tagline': '在欢乐中学习的魔法故事',
    'footer.rights': '版权所有。',
    'grades.title': '你在几年级？',
    'grades.subtitle': '选择你的年级来发现适合的冒险！',
    'general.loading': '加载中...',
    'general.error': '错误',
    'general.success': '成功',
    'general.cancel': '取消',
    'general.save': '保存',
    'general.delete': '删除',
    'general.edit': '编辑',
    'general.close': '关闭',
  },
  'pt-br': {
    'nav.back': 'Voltar',
    'nav.backToSubjects': 'Voltar às matérias',
    'nav.backToStories': 'Voltar às histórias',
    'nav.quitStory': 'Sair da história',
    'nav.home': 'Início',
    'auth.login': 'Entrar',
    'auth.logout': 'Sair',
    'auth.register': 'Criar conta',
    'auth.noAccount': 'Não tem conta?',
    'auth.hasAccount': 'Já tem conta?',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.firstName': 'Nome',
    'auth.loginTitle': 'Entrar',
    'auth.registerTitle': 'Criar conta',
    'auth.loginSubtitle': 'Encontre suas histórias e progresso!',
    'auth.registerSubtitle': 'Junte-se aos heróis da classe!',
    'auth.loginSuccess': 'Login bem-sucedido!',
    'auth.welcomeBack': 'Bem-vindo de volta!',
    'auth.loginError': 'Erro de login',
    'auth.invalidCredentials': 'E-mail ou senha incorretos.',
    'auth.error': 'Erro',
    'auth.genericError': 'Ocorreu um erro. Tente novamente mais tarde.',
    'auth.submit': 'Entrar',
    'auth.createAccount': 'Criar minha conta',
    'menu.myAccount': 'Minha conta',
    'menu.changeAvatar': 'Mudar avatar',
    'menu.myStories': 'Minhas histórias',
    'menu.admin': 'Administração',
    'menu.seeYou': 'Até logo!',
    'menu.loggedOut': 'Você saiu da conta.',
    'menu.adventurer': 'Aventureiro',
    'avatar.chooseTitle': 'Escolha seu avatar',
    'avatar.chooseSubtitle': 'Selecione o personagem que se parece com você!',
    'avatar.cancel': 'Cancelar',
    'avatar.save': 'Salvar',
    'avatar.saving': 'Salvando...',
    'avatar.changed': 'Avatar alterado!',
    'avatar.changedDesc': 'Seu novo avatar está incrível!',
    'avatar.error': 'Não foi possível alterar o avatar',
    'stories.chooseAdventure': 'Escolha sua aventura!',
    'stories.saveProgress': 'Salvar meu progresso',
    'stories.loading': 'Carregando histórias...',
    'stories.noStories': 'Nenhuma história disponível para esta matéria em',
    'stories.chooseOther': 'Escolher outra matéria',
    'story.pageNotFound': 'Página não encontrada',
    'story.pageNotFoundDesc': 'Esta página não existe.',
    'story.backToStories': 'Voltar às histórias',
    'story.endingHappy': 'Fim da história!',
    'story.endingAlt': 'Outro final...',
    'story.listenStory': 'Ouvir a história',
    'story.stopListening': 'Parar',
    'story.downloadColoring': 'Colorir dinossauros',
    'story.whatToDo': 'O que você quer fazer?',
    'story.restart': 'Recomeçar esta história',
    'story.otherStories': 'Outras histórias',
    'start.enterName': 'Digite seu nome',
    'start.yourName': 'Seu nome',
    'start.namePlaceholder': 'Ex: Emma, Lucas...',
    'start.nameHint': 'Seu nome aparecerá na história!',
    'start.chooseGender': 'Escolha seu gênero',
    'start.genderMasculine': 'Masculino',
    'start.genderFeminine': 'Feminino',
    'start.genderNeutral': 'Neutro',
    'start.genderHint': 'Isso adaptará algumas palavras da história.',
    'start.beginAdventure': 'Vamos começar a aventura!',
    'start.back': 'Voltar',
    'footer.tagline': 'Histórias mágicas para aprender brincando',
    'footer.rights': 'Todos os direitos reservados.',
    'grades.title': 'Em que série você está?',
    'grades.subtitle': 'Escolha sua série para descobrir aventuras adaptadas!',
    'general.loading': 'Carregando...',
    'general.error': 'Erro',
    'general.success': 'Sucesso',
    'general.cancel': 'Cancelar',
    'general.save': 'Salvar',
    'general.delete': 'Excluir',
    'general.edit': 'Editar',
    'general.close': 'Fechar',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('preferred-language');
    return (saved as Language) || 'fr';
  });
  const [isTranslating, setIsTranslating] = useState(false);

  useEffect(() => {
    localStorage.setItem('preferred-language', language);
    document.documentElement.lang = language === 'pt-br' ? 'pt-BR' : language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.fr[key] || key;
  };

  const translateText = async (text: string, targetLang?: Language): Promise<string> => {
    const lang = targetLang || language;
    if (lang === 'fr') return text; // No translation needed for French

    setIsTranslating(true);
    try {
      const response = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/translate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
        },
        body: JSON.stringify({ text, targetLanguage: lang }),
      });

      if (!response.ok) {
        console.error('Translation error:', response.status);
        return text;
      }

      const data = await response.json();
      return data.translatedText || text;
    } catch (error) {
      console.error('Translation failed:', error);
      return text;
    } finally {
      setIsTranslating(false);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translateText, isTranslating }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
