import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'de' | 'ru' | 'es' | 'zh' | 'pt-br';

export interface LanguageConfig {
  code: Language;
  name: string;
  flag: string;
}

export const languages: LanguageConfig[] = [
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'pt-br', name: 'Português (BR)', flag: '🇧🇷' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translateText: (text: string, targetLang?: Language) => Promise<string>;
  isTranslating: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// UI translations for each language
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.back': 'Retour',
    'nav.backToSubjects': 'Retour aux matières',
    'nav.backToStories': 'Retour aux histoires',
    'nav.quitStory': "Quitter l'histoire",
    'nav.home': 'Accueil',
    
    // Auth
    'auth.login': 'Connexion',
    'auth.logout': 'Se déconnecter',
    'auth.register': 'Créer un compte',
    'auth.noAccount': 'Pas encore de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.firstName': 'Prénom',
    'auth.loginTitle': 'Connexion',
    'auth.registerTitle': 'Créer un compte',
    'auth.loginSubtitle': 'Retrouve tes histoires et ta progression !',
    'auth.registerSubtitle': 'Rejoins les héros de la classe !',
    'auth.loginSuccess': 'Connexion réussie !',
    'auth.loginSuccessDesc': 'Content de te revoir !',
    'auth.welcomeBack': 'Content de te revoir !',
    'auth.loginError': 'Erreur de connexion',
    'auth.invalidCredentials': 'Email ou mot de passe incorrect.',
    'auth.error': 'Erreur',
    'auth.genericError': 'Une erreur est survenue. Réessayez plus tard.',
    'auth.submit': 'Se connecter',
    'auth.loginButton': 'Se connecter',
    'auth.registerButton': 'Créer mon compte',
    'auth.createAccount': 'Créer mon compte',
    'auth.passwordMismatch': 'Les mots de passe ne correspondent pas.',
    'auth.accountExists': 'Ce compte existe déjà.',
    'auth.registerSuccess': 'Compte créé !',
    'auth.registerSuccessDesc': 'Bienvenue parmi les héros !',
    
    // User Menu
    'menu.myAccount': 'Mon compte',
    'menu.changeAvatar': "Changer d'avatar",
    'menu.myStories': 'Mes histoires',
    'menu.admin': 'Administration',
    'menu.seeYou': 'À bientôt !',
    'menu.loggedOut': 'Tu as été déconnecté.',
    'menu.adventurer': 'Aventurier',
    
    // Avatar Dialog
    'avatar.chooseTitle': 'Choisis ton avatar',
    'avatar.chooseSubtitle': 'Sélectionne le personnage qui te ressemble !',
    'avatar.cancel': 'Annuler',
    'avatar.save': 'Enregistrer',
    'avatar.saving': 'Enregistrement...',
    'avatar.changed': 'Avatar modifié !',
    'avatar.changedDesc': 'Ton nouvel avatar est super !',
    'avatar.error': "Impossible de changer l'avatar",
    
    // Stories Dashboard
    'stories.chooseAdventure': 'Choisis ton aventure !',
    'stories.saveProgress': 'Enregistrer ma progression',
    'stories.loading': 'Chargement des histoires...',
    'stories.noStories': 'Aucune histoire disponible pour cette matière en',
    'stories.chooseOther': 'Choisir une autre matière',
    
    // Story Reader
    'story.pageNotFound': 'Page introuvable',
    'story.pageNotFoundDesc': "Cette page n'existe pas.",
    'story.backToStories': 'Retour aux histoires',
    'story.endingHappy': "Fin de l'histoire !",
    'story.endingAlt': 'Une autre fin...',
    'story.listenStory': "Écouter l'histoire",
    'story.stopListening': 'Arrêter',
    'story.downloadColoring': 'Coloriage dinosaures',
    'story.whatToDo': 'Que veux-tu faire ?',
    'story.restart': 'Recommencer cette histoire',
    'story.otherStories': 'Autres histoires',
    
    // Story Start
    'start.enterName': 'Entre ton prénom',
    'start.yourName': 'Ton prénom',
    'start.namePlaceholder': 'Ex: Emma, Lucas...',
    'start.nameHint': 'Ton prénom apparaîtra dans l\'histoire !',
    'start.chooseGender': 'Choisis ton genre',
    'start.genderMasculine': 'Masculin',
    'start.genderFeminine': 'Féminin',
    'start.genderNeutral': 'Neutre',
    'start.genderHint': 'Cela adaptera certains mots de l\'histoire.',
    'start.beginAdventure': "C'est parti pour l'aventure !",
    'start.back': 'Retour',
    
    // Footer
    'footer.tagline': 'Des histoires magiques pour apprendre en s\'amusant',
    'footer.rights': 'Tous droits réservés.',
    'footer.why': 'Pourquoi ce site ?',
    'footer.whyText1': 'Je suis fan de jeux de rôle, d\'informatique et bientôt papa.',
    'footer.whyText2': 'Je suis parti d\'un constat simple : le programme scolaire existe, mais la façon de l\'apprendre ne convient pas à tous les enfants.',
    'footer.whyText3': 'J\'ai donc créé un site éducatif sous forme de livre dont vous êtes le héros. L\'enfant devient le personnage principal, fait des choix, avance dans une histoire… et apprend le programme scolaire sans s\'en rendre compte.',
    'footer.whyText4': 'Ça commence au CP, avec une ambition claire : construire chaque niveau, classe après classe. Aujourd\'hui, il y a déjà plusieurs histoires, encore un peu exploratoires, mais les retours sont très positifs.',
    'footer.whyText5': 'L\'objectif maintenant : enrichir l\'univers, ajouter de plus en plus d\'aventures, et proposer une alternative plus engageante, plus ludique, et peut-être plus adaptée à la diversité des enfants.',
    'footer.contact': 'Une idée ? Une question ?',
    'footer.contactText': 'N\'hésite pas à me contacter sur',

    // Subjects
    'subjects.subtitle': 'Choisis une matière pour découvrir des histoires passionnantes !',
    'subjects.lecture.name': 'Français',
    'subjects.lecture': 'Histoires interactives pour apprendre à lire',
    'subjects.mathematiques.name': 'Mathématiques',
    'subjects.mathematiques': 'Aventures pour découvrir les nombres',
    'subjects.histoire.name': 'Histoire',
    'subjects.histoire': 'Voyages dans le temps et découvertes',
    'subjects.geographie.name': 'Géographie',
    'subjects.geographie': 'Explorations du monde entier',
    'subjects.sciences.name': 'Sciences',
    'subjects.sciences': 'Expériences et découvertes scientifiques',
    'subjects.langues.name': 'Langues',
    'subjects.langues': 'Apprendre l\'anglais en s\'amusant',
    // Stories
    'stories.notFound': 'Histoire introuvable',
    'stories.notFoundDesc': 'Cette histoire n\'existe pas ou a été supprimée.',

    // Start page
    'start.customize': 'Personnalise ton aventure',
    'start.ready': 'Prêt',
    'start.begin': 'C\'est parti !',

    // Nav
    'nav.backToGrades': 'Retour aux niveaux',

    // Grades
    'grades.title': 'À quel niveau es-tu ?',
    'grades.subtitle': 'Choisis ta classe pour découvrir des aventures adaptées !',
    'grades.cp.fullName': 'Cours Préparatoire',
    'grades.cp.description': 'Premières aventures de lecture',
    'grades.ce1.fullName': 'Cours Élémentaire 1',
    'grades.ce1.description': 'Découvertes et explorations',
    'grades.ce2.fullName': 'Cours Élémentaire 2',
    'grades.ce2.description': 'Voyages et sciences',
    'grades.cm1.fullName': 'Cours Moyen 1',
    'grades.cm1.description': 'Histoire et découvertes',
    'grades.cm2.fullName': 'Cours Moyen 2',
    'grades.cm2.description': 'Aventures avancées',
    
    // My Stories
    'myStories.title': 'Mes histoires',
    'myStories.greeting': 'Bienvenue {name} !',
    'myStories.createProfile': 'Créer un profil',
    'myStories.createProfileDesc': 'Crée un profil pour sauvegarder ta progression et suivre tes histoires !',
    'myStories.completed': 'Histoires terminées',
    'myStories.endings': 'Fins découvertes',
    'myStories.inProgress': 'En cours',
    'myStories.continueReading': 'Continuer la lecture',
    'myStories.toDiscover': 'À découvrir',
    'myStories.completedStories': 'Histoires terminées',
    'myStories.noCompleted': "Tu n'as pas encore terminé d'histoire. Lance-toi dans une aventure !",
    'myStories.discover': 'Découvrir les histoires',
    'myStories.replay': 'Rejouer',
    
    // Stories continue button
    'stories.continue': 'Continuer',
    'stories.title': 'Choisis ton aventure !',
    'stories.readStory': 'Lire l\'histoire',
    'stories.restart': 'Recommencer cette histoire',
    'stories.otherStories': 'Autres histoires',
    'stories.pageNotFound': 'Page introuvable',
    'stories.pageNotFoundDesc': 'Cette page n\'existe pas.',

    // Reader
    'reader.endingHappy': 'Fin de l\'histoire !',
    'reader.endingAlt': 'Une autre fin...',
    'reader.stop': 'Arrêter',
    'reader.listen': 'Écouter l\'histoire',
    'reader.coloringDownload': 'Coloriage dinosaures',
    'reader.whatToDo': 'Que veux-tu faire ?',

    // Cards
    'card.completed': 'Terminée',
    'card.inProgress': 'En cours',
    'card.letsGo': 'C\'est parti !',
    'card.comingSoon': 'Bientôt disponible',
    'card.share': 'Partager :',
    'card.shareThis': 'Partager ce site',

    // Account benefits
    'account.whyCreate': 'Pourquoi créer un compte ?',
    'account.profileDesc': 'Créez un profil pour chaque enfant avec son avatar et son prénom pour des histoires plus immersives.',
    'account.historyDesc': 'Retrouvez facilement les lectures en cours et reprenez exactement là où vous vous êtes arrêtés.',
    'account.trackingDesc': 'Visualisez les histoires déjà lues et celles qui restent à découvrir pour chaque enfant.',
    'account.benefitText': 'Créer un compte, c\'est la garantie d\'un suivi simple, d\'une lecture fluide et d\'une expérience personnalisée qui évolue au rythme de vos enfants.',
    'account.createFree': 'Créer un compte gratuit',

    // Nav additional
    'nav.leaveStory': 'Quitter l\'histoire',
    
    // Common
    'common.loading': 'Chargement...',
    'common.completed': 'Terminé',
    'common.ends': 'fins',
    'common.end': 'fin',
    
    // General
    'general.loading': 'Chargement...',
    'general.error': 'Erreur',
    'general.success': 'Succès',
    'general.cancel': 'Annuler',
    'general.save': 'Enregistrer',
    'general.delete': 'Supprimer',
    'general.edit': 'Modifier',
    'general.close': 'Fermer',

    // Editor
    'editor.adminMode': 'Mode édition admin',
    'editor.placeholder': 'Texte de la page...',
    'editor.textUpdated': 'Texte mis à jour pour tous les utilisateurs',
    'editor.saveError': 'Erreur lors de la sauvegarde',
    'editor.textRestored': 'Texte restauré à la version originale',
    'editor.restoreError': 'Erreur lors de la restauration',
    'editor.restoreOriginal': 'Restaurer l\'original',
    'editor.modified': 'modifié',

    // Inventory
    'inventory.title': 'Inventaire',
    'inventory.newItem': 'Nouvel objet !',
  },
  en: {
    // Navigation
    'nav.back': 'Back',
    'nav.backToSubjects': 'Back to subjects',
    'nav.backToStories': 'Back to stories',
    'nav.quitStory': 'Quit story',
    'nav.home': 'Home',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Log out',
    'auth.register': 'Create account',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm password',
    'auth.firstName': 'First name',
    'auth.loginTitle': 'Login',
    'auth.registerTitle': 'Create account',
    'auth.loginSubtitle': 'Find your stories and progress!',
    'auth.registerSubtitle': 'Join the class heroes!',
    'auth.loginSuccess': 'Login successful!',
    'auth.loginSuccessDesc': 'Welcome back!',
    'auth.welcomeBack': 'Welcome back!',
    'auth.loginError': 'Login error',
    'auth.invalidCredentials': 'Invalid email or password.',
    'auth.error': 'Error',
    'auth.genericError': 'An error occurred. Try again later.',
    'auth.submit': 'Log in',
    'auth.loginButton': 'Log in',
    'auth.registerButton': 'Create my account',
    'auth.createAccount': 'Create my account',
    'auth.passwordMismatch': 'Passwords do not match.',
    'auth.accountExists': 'This account already exists.',
    'auth.registerSuccess': 'Account created!',
    'auth.registerSuccessDesc': 'Welcome among the heroes!',
    
    // User Menu
    'menu.myAccount': 'My account',
    'menu.changeAvatar': 'Change avatar',
    'menu.myStories': 'My stories',
    'menu.admin': 'Administration',
    'menu.seeYou': 'See you soon!',
    'menu.loggedOut': 'You have been logged out.',
    'menu.adventurer': 'Adventurer',
    
    // Avatar Dialog
    'avatar.chooseTitle': 'Choose your avatar',
    'avatar.chooseSubtitle': 'Select the character that looks like you!',
    'avatar.cancel': 'Cancel',
    'avatar.save': 'Save',
    'avatar.saving': 'Saving...',
    'avatar.changed': 'Avatar changed!',
    'avatar.changedDesc': 'Your new avatar looks great!',
    'avatar.error': 'Unable to change avatar',
    
    // Stories Dashboard
    'stories.chooseAdventure': 'Choose your adventure!',
    'stories.saveProgress': 'Save my progress',
    'stories.loading': 'Loading stories...',
    'stories.noStories': 'No stories available for this subject in',
    'stories.chooseOther': 'Choose another subject',
    
    // Story Reader
    'story.pageNotFound': 'Page not found',
    'story.pageNotFoundDesc': 'This page does not exist.',
    'story.backToStories': 'Back to stories',
    'story.endingHappy': 'The End!',
    'story.endingAlt': 'Another ending...',
    'story.listenStory': 'Listen to the story',
    'story.stopListening': 'Stop',
    'story.downloadColoring': 'Dinosaur coloring',
    'story.whatToDo': 'What do you want to do?',
    'story.restart': 'Restart this story',
    'story.otherStories': 'Other stories',
    
    // Story Start
    'start.enterName': 'Enter your name',
    'start.yourName': 'Your name',
    'start.namePlaceholder': 'E.g: Emma, Lucas...',
    'start.nameHint': 'Your name will appear in the story!',
    'start.chooseGender': 'Choose your gender',
    'start.genderMasculine': 'Masculine',
    'start.genderFeminine': 'Feminine',
    'start.genderNeutral': 'Neutral',
    'start.genderHint': 'This will adapt some words in the story.',
    'start.beginAdventure': "Let's start the adventure!",
    'start.back': 'Back',
    
    // Footer
    'footer.tagline': 'Magical stories to learn while having fun',
    'footer.rights': 'All rights reserved.',
    'footer.why': 'Why this site?',
    'footer.whyText1': 'I\'m a fan of role-playing games, computers, and soon to be a dad.',
    'footer.whyText2': 'I started from a simple observation: the school curriculum exists, but the way of learning it doesn\'t suit all children.',
    'footer.whyText3': 'So I created an educational site in the form of a choose-your-own-adventure book. The child becomes the main character, makes choices, advances through a story... and learns the curriculum without realizing it.',
    'footer.whyText4': 'It starts in kindergarten, with a clear ambition: to build each level, class by class. Today, there are already several stories, still a bit exploratory, but the feedback is very positive.',
    'footer.whyText5': 'The goal now: to enrich the universe, add more and more adventures, and offer a more engaging, more playful, and perhaps more suitable alternative for the diversity of children.',
    'footer.contact': 'Got an idea? A question?',
    'footer.contactText': 'Feel free to contact me on',

    // Subjects
    'subjects.subtitle': 'Choose a subject to discover exciting stories!',
    'subjects.lecture.name': 'French',
    'subjects.lecture': 'Interactive stories to learn to read',
    'subjects.mathematiques.name': 'Mathematics',
    'subjects.mathematiques': 'Adventures to discover numbers',
    'subjects.histoire.name': 'History',
    'subjects.histoire': 'Time travel and discoveries',
    'subjects.geographie.name': 'Geography',
    'subjects.geographie': 'Explorations around the world',
    'subjects.sciences.name': 'Science',
    'subjects.sciences': 'Experiments and scientific discoveries',
    'subjects.langues.name': 'Languages',
    'subjects.langues': 'Learn English while having fun',

    // Stories
    'stories.notFound': 'Story not found',
    'stories.notFoundDesc': 'This story does not exist or has been deleted.',

    // Start page
    'start.customize': 'Customize your adventure',
    'start.ready': 'Ready',
    'start.begin': 'Let\'s go!',

    // Nav
    'nav.backToGrades': 'Back to grades',

    // Grades
    'grades.title': 'What grade are you in?',
    'grades.subtitle': 'Choose your class to discover tailored adventures!',
    'grades.cp.fullName': 'Kindergarten',
    'grades.cp.description': 'First reading adventures',
    'grades.ce1.fullName': 'Grade 1',
    'grades.ce1.description': 'Discoveries and explorations',
    'grades.ce2.fullName': 'Grade 2',
    'grades.ce2.description': 'Travels and sciences',
    'grades.cm1.fullName': 'Grade 3',
    'grades.cm1.description': 'History and discoveries',
    'grades.cm2.fullName': 'Grade 4',
    'grades.cm2.description': 'Advanced adventures',
    
    // My Stories
    'myStories.title': 'My Stories',
    'myStories.greeting': 'Welcome {name}!',
    'myStories.createProfile': 'Create a profile',
    'myStories.createProfileDesc': 'Create a profile to save your progress and track your stories!',
    'myStories.completed': 'Stories completed',
    'myStories.endings': 'Endings discovered',
    'myStories.inProgress': 'In progress',
    'myStories.continueReading': 'Continue reading',
    'myStories.toDiscover': 'To discover',
    'myStories.completedStories': 'Completed stories',
    'myStories.noCompleted': "You haven't finished any story yet. Start an adventure!",
    'myStories.discover': 'Discover stories',
    'myStories.replay': 'Replay',
    
    // Stories continue button
    'stories.continue': 'Continue',
    'stories.title': 'Choose your adventure!',
    'stories.readStory': 'Read the story',
    'stories.restart': 'Restart this story',
    'stories.otherStories': 'Other stories',
    'stories.pageNotFound': 'Page not found',
    'stories.pageNotFoundDesc': 'This page does not exist.',

    // Reader
    'reader.endingHappy': 'The End!',
    'reader.endingAlt': 'Another ending...',
    'reader.stop': 'Stop',
    'reader.listen': 'Listen to the story',
    'reader.coloringDownload': 'Dinosaur coloring',
    'reader.whatToDo': 'What do you want to do?',

    // Cards
    'card.completed': 'Completed',
    'card.inProgress': 'In progress',
    'card.letsGo': 'Let\'s go!',
    'card.comingSoon': 'Coming soon',
    'card.share': 'Share:',
    'card.shareThis': 'Share this site',

    // Inventory
    'inventory.title': 'Inventory',
    'inventory.newItem': 'New item!',

    // Account benefits
    'account.whyCreate': 'Why create an account?',
    'account.profileDesc': 'Create a profile for each child with their avatar and name for more immersive stories.',
    'account.historyDesc': 'Easily find ongoing readings and pick up exactly where you left off.',
    'account.trackingDesc': 'See which stories have been read and which ones are left to discover for each child.',
    'account.benefitText': 'Creating an account ensures simple tracking, smooth reading, and a personalized experience that grows with your children.',
    'account.createFree': 'Create a free account',

    // Nav additional
    'nav.leaveStory': 'Leave story',
    
    // Common
    'common.loading': 'Loading...',
    'common.completed': 'Completed',
    'common.ends': 'endings',
    'common.end': 'ending',
    
    // General
    'general.loading': 'Loading...',
    'general.error': 'Error',
    'general.success': 'Success',
    'general.cancel': 'Cancel',
    'general.save': 'Save',
    'general.delete': 'Delete',
    'general.edit': 'Edit',
    'general.close': 'Close',

    // Editor
    'editor.adminMode': 'Admin editing mode',
    'editor.placeholder': 'Page text...',
    'editor.textUpdated': 'Text updated for all users',
    'editor.saveError': 'Error while saving',
    'editor.textRestored': 'Text restored to original version',
    'editor.restoreError': 'Error while restoring',
    'editor.restoreOriginal': 'Restore original',
    'editor.modified': 'modified',
  },
  de: {
    'nav.back': 'Zurück',
    'nav.backToSubjects': 'Zurück zu den Fächern',
    'nav.backToStories': 'Zurück zu den Geschichten',
    'nav.quitStory': 'Geschichte beenden',
    'nav.home': 'Startseite',
    'auth.login': 'Anmelden',
    'auth.logout': 'Abmelden',
    'auth.register': 'Konto erstellen',
    'auth.noAccount': 'Noch kein Konto?',
    'auth.hasAccount': 'Bereits ein Konto?',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.firstName': 'Vorname',
    'auth.loginTitle': 'Anmelden',
    'auth.registerTitle': 'Konto erstellen',
    'auth.loginSubtitle': 'Finde deine Geschichten und deinen Fortschritt!',
    'auth.registerSubtitle': 'Werde ein Klassenheld!',
    'auth.loginSuccess': 'Erfolgreich angemeldet!',
    'auth.loginSuccessDesc': 'Willkommen zurück!',
    'auth.welcomeBack': 'Willkommen zurück!',
    'auth.loginError': 'Anmeldefehler',
    'auth.invalidCredentials': 'Ungültige E-Mail oder Passwort.',
    'auth.error': 'Fehler',
    'auth.genericError': 'Ein Fehler ist aufgetreten. Versuche es später erneut.',
    'auth.submit': 'Anmelden',
    'auth.loginButton': 'Anmelden',
    'auth.registerButton': 'Mein Konto erstellen',
    'auth.createAccount': 'Mein Konto erstellen',
    'auth.passwordMismatch': 'Passwörter stimmen nicht überein.',
    'auth.accountExists': 'Dieses Konto existiert bereits.',
    'auth.registerSuccess': 'Konto erstellt!',
    'auth.registerSuccessDesc': 'Willkommen bei den Helden!',
    'menu.myAccount': 'Mein Konto',
    'menu.changeAvatar': 'Avatar ändern',
    'menu.myStories': 'Meine Geschichten',
    'menu.admin': 'Administration',
    'menu.seeYou': 'Bis bald!',
    'menu.loggedOut': 'Du wurdest abgemeldet.',
    'menu.adventurer': 'Abenteurer',
    'avatar.chooseTitle': 'Wähle deinen Avatar',
    'avatar.chooseSubtitle': 'Wähle die Figur, die dir ähnelt!',
    'avatar.cancel': 'Abbrechen',
    'avatar.save': 'Speichern',
    'avatar.saving': 'Speichern...',
    'avatar.changed': 'Avatar geändert!',
    'avatar.changedDesc': 'Dein neuer Avatar sieht toll aus!',
    'avatar.error': 'Avatar konnte nicht geändert werden',
    'stories.chooseAdventure': 'Wähle dein Abenteuer!',
    'stories.saveProgress': 'Meinen Fortschritt speichern',
    'stories.loading': 'Geschichten werden geladen...',
    'stories.noStories': 'Keine Geschichten für dieses Fach in',
    'stories.chooseOther': 'Ein anderes Fach wählen',
    'story.pageNotFound': 'Seite nicht gefunden',
    'story.pageNotFoundDesc': 'Diese Seite existiert nicht.',
    'story.backToStories': 'Zurück zu den Geschichten',
    'story.endingHappy': 'Ende der Geschichte!',
    'story.endingAlt': 'Ein anderes Ende...',
    'story.listenStory': 'Geschichte anhören',
    'story.stopListening': 'Stoppen',
    'story.downloadColoring': 'Dinosaurier-Ausmalbild',
    'story.whatToDo': 'Was möchtest du tun?',
    'story.restart': 'Diese Geschichte neu starten',
    'story.otherStories': 'Andere Geschichten',
    'start.enterName': 'Gib deinen Namen ein',
    'start.yourName': 'Dein Name',
    'start.namePlaceholder': 'Z.B: Emma, Lucas...',
    'start.nameHint': 'Dein Name erscheint in der Geschichte!',
    'start.chooseGender': 'Wähle dein Geschlecht',
    'start.genderMasculine': 'Männlich',
    'start.genderFeminine': 'Weiblich',
    'start.genderNeutral': 'Neutral',
    'start.genderHint': 'Dies passt einige Wörter in der Geschichte an.',
    'start.beginAdventure': 'Auf ins Abenteuer!',
    'start.back': 'Zurück',
    'footer.tagline': 'Magische Geschichten zum spielerischen Lernen',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.why': 'Warum diese Seite?',
    'footer.whyText1': 'Ich bin Fan von Rollenspielen, Informatik und werde bald Vater.',
    'footer.whyText2': 'Ich ging von einer einfachen Feststellung aus: Der Lehrplan existiert, aber die Art zu lernen passt nicht zu allen Kindern.',
    'footer.whyText3': 'Also habe ich eine Bildungsseite als Spielbuch erstellt. Das Kind wird zur Hauptfigur, trifft Entscheidungen, geht durch eine Geschichte... und lernt den Lehrplan, ohne es zu merken.',
    'footer.whyText4': 'Es beginnt in der Vorschule mit einem klaren Ziel: jede Stufe aufzubauen, Klasse für Klasse. Heute gibt es bereits mehrere Geschichten, noch etwas experimentell, aber das Feedback ist sehr positiv.',
    'footer.whyText5': 'Das Ziel jetzt: das Universum bereichern, mehr Abenteuer hinzufügen und eine ansprechendere Alternative bieten, die besser zur Vielfalt der Kinder passt.',
    'footer.contact': 'Eine Idee? Eine Frage?',
    'footer.contactText': 'Kontaktiere mich gerne auf',
    'subjects.subtitle': 'Wähle ein Fach, um spannende Geschichten zu entdecken!',
    'subjects.lecture.name': 'Französisch',
    'subjects.lecture': 'Interaktive Geschichten zum Lesenlernen',
    'subjects.mathematiques.name': 'Mathematik',
    'subjects.mathematiques': 'Abenteuer zum Entdecken von Zahlen',
    'subjects.histoire.name': 'Geschichte',
    'subjects.histoire': 'Zeitreisen und Entdeckungen',
    'subjects.geographie.name': 'Geographie',
    'subjects.geographie': 'Erkundungen der ganzen Welt',
    'subjects.sciences.name': 'Wissenschaft',
    'subjects.sciences': 'Experimente und wissenschaftliche Entdeckungen',
    'subjects.langues.name': 'Sprachen',
    'subjects.langues': 'Englisch lernen mit Spaß',
    'stories.notFound': 'Geschichte nicht gefunden',
    'stories.notFoundDesc': 'Diese Geschichte existiert nicht oder wurde gelöscht.',
    'start.customize': 'Passe dein Abenteuer an',
    'start.ready': 'Bereit',
    'start.begin': 'Los geht\'s!',
    'nav.backToGrades': 'Zurück zu den Stufen',
    'grades.title': 'In welcher Klasse bist du?',
    'grades.subtitle': 'Wähle deine Klasse für passende Abenteuer!',
    'grades.cp.fullName': 'Vorschule',
    'grades.cp.description': 'Erste Leseabenteuer',
    'grades.ce1.fullName': '1. Klasse',
    'grades.ce1.description': 'Entdeckungen und Erkundungen',
    'grades.ce2.fullName': '2. Klasse',
    'grades.ce2.description': 'Reisen und Wissenschaften',
    'grades.cm1.fullName': '3. Klasse',
    'grades.cm1.description': 'Geschichte und Entdeckungen',
    'grades.cm2.fullName': '4. Klasse',
    'grades.cm2.description': 'Fortgeschrittene Abenteuer',
    'myStories.title': 'Meine Geschichten',
    'myStories.greeting': 'Willkommen {name}!',
    'myStories.createProfile': 'Profil erstellen',
    'myStories.createProfileDesc': 'Erstelle ein Profil, um deinen Fortschritt zu speichern!',
    'myStories.completed': 'Abgeschlossene Geschichten',
    'myStories.endings': 'Entdeckte Enden',
    'myStories.inProgress': 'In Bearbeitung',
    'myStories.continueReading': 'Weiterlesen',
    'myStories.toDiscover': 'Zu entdecken',
    'myStories.completedStories': 'Abgeschlossene Geschichten',
    'myStories.noCompleted': 'Du hast noch keine Geschichte beendet. Starte ein Abenteuer!',
    'myStories.discover': 'Geschichten entdecken',
    'myStories.replay': 'Nochmal spielen',
    'stories.continue': 'Fortsetzen',
    'stories.title': 'Wähle dein Abenteuer!',
    'stories.readStory': 'Geschichte lesen',
    'stories.restart': 'Diese Geschichte neu starten',
    'stories.otherStories': 'Andere Geschichten',
    'stories.pageNotFound': 'Seite nicht gefunden',
    'stories.pageNotFoundDesc': 'Diese Seite existiert nicht.',
    'reader.endingHappy': 'Ende der Geschichte!',
    'reader.endingAlt': 'Ein anderes Ende...',
    'reader.stop': 'Stoppen',
    'reader.listen': 'Geschichte anhören',
    'reader.coloringDownload': 'Dinosaurier-Ausmalbild',
    'reader.whatToDo': 'Was möchtest du tun?',
    'card.completed': 'Abgeschlossen',
    'card.inProgress': 'In Bearbeitung',
    'card.letsGo': 'Los geht\'s!',
    'card.comingSoon': 'Bald verfügbar',
    'card.share': 'Teilen:',
    'card.shareThis': 'Diese Seite teilen',
    'account.whyCreate': 'Warum ein Konto erstellen?',
    'account.profileDesc': 'Erstelle für jedes Kind ein Profil mit Avatar und Namen für mehr Immersion.',
    'account.historyDesc': 'Finde laufende Lesungen leicht und setze genau dort fort, wo du aufgehört hast.',
    'account.trackingDesc': 'Sieh, welche Geschichten gelesen wurden und welche noch zu entdecken sind.',
    'account.benefitText': 'Ein Konto garantiert einfaches Tracking und ein personalisiertes Erlebnis.',
    'account.createFree': 'Kostenloses Konto erstellen',
    'nav.leaveStory': 'Geschichte verlassen',
    'common.loading': 'Laden...',
    'common.completed': 'Abgeschlossen',
    'common.ends': 'Enden',
    'common.end': 'Ende',
    'general.loading': 'Laden...',
    'general.error': 'Fehler',
    'general.success': 'Erfolg',
    'general.cancel': 'Abbrechen',
    'general.save': 'Speichern',
    'general.delete': 'Löschen',
    'general.edit': 'Bearbeiten',
    'general.close': 'Schließen',
    'editor.adminMode': 'Admin-Bearbeitungsmodus',
    'editor.placeholder': 'Seitentext...',
    'editor.textUpdated': 'Text für alle Benutzer aktualisiert',
    'editor.saveError': 'Fehler beim Speichern',
    'editor.textRestored': 'Text auf Originalversion zurückgesetzt',
    'editor.restoreError': 'Fehler beim Wiederherstellen',
    'editor.restoreOriginal': 'Original wiederherstellen',
    'editor.modified': 'geändert',

    // Inventory
    'inventory.title': 'Inventar',
    'inventory.newItem': 'Neuer Gegenstand!',
  },
  ru: {
    'nav.back': 'Назад',
    'nav.backToSubjects': 'Вернуться к предметам',
    'nav.backToStories': 'Вернуться к историям',
    'nav.quitStory': 'Выйти из истории',
    'nav.home': 'Главная',
    'auth.login': 'Войти',
    'auth.logout': 'Выйти',
    'auth.register': 'Создать аккаунт',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.hasAccount': 'Уже есть аккаунт?',
    'auth.email': 'Электронная почта',
    'auth.password': 'Пароль',
    'auth.confirmPassword': 'Подтвердить пароль',
    'auth.firstName': 'Имя',
    'auth.loginTitle': 'Вход',
    'auth.registerTitle': 'Создать аккаунт',
    'auth.loginSubtitle': 'Найди свои истории и прогресс!',
    'auth.registerSubtitle': 'Присоединяйся к героям класса!',
    'auth.loginSuccess': 'Вход выполнен!',
    'auth.loginSuccessDesc': 'С возвращением!',
    'auth.welcomeBack': 'С возвращением!',
    'auth.loginError': 'Ошибка входа',
    'auth.invalidCredentials': 'Неверный email или пароль.',
    'auth.error': 'Ошибка',
    'auth.genericError': 'Произошла ошибка. Попробуйте позже.',
    'auth.submit': 'Войти',
    'auth.loginButton': 'Войти',
    'auth.registerButton': 'Создать аккаунт',
    'auth.createAccount': 'Создать аккаунт',
    'auth.passwordMismatch': 'Пароли не совпадают.',
    'auth.accountExists': 'Этот аккаунт уже существует.',
    'auth.registerSuccess': 'Аккаунт создан!',
    'auth.registerSuccessDesc': 'Добро пожаловать к героям!',
    'menu.myAccount': 'Мой аккаунт',
    'menu.changeAvatar': 'Изменить аватар',
    'menu.myStories': 'Мои истории',
    'menu.admin': 'Администрация',
    'menu.seeYou': 'До скорой встречи!',
    'menu.loggedOut': 'Вы вышли из системы.',
    'menu.adventurer': 'Искатель приключений',
    'avatar.chooseTitle': 'Выбери свой аватар',
    'avatar.chooseSubtitle': 'Выбери персонажа, который похож на тебя!',
    'avatar.cancel': 'Отмена',
    'avatar.save': 'Сохранить',
    'avatar.saving': 'Сохранение...',
    'avatar.changed': 'Аватар изменён!',
    'avatar.changedDesc': 'Твой новый аватар отлично выглядит!',
    'avatar.error': 'Не удалось изменить аватар',
    'stories.chooseAdventure': 'Выбери своё приключение!',
    'stories.saveProgress': 'Сохранить прогресс',
    'stories.loading': 'Загрузка историй...',
    'stories.noStories': 'Нет историй для этого предмета в',
    'stories.chooseOther': 'Выбрать другой предмет',
    'story.pageNotFound': 'Страница не найдена',
    'story.pageNotFoundDesc': 'Эта страница не существует.',
    'story.backToStories': 'Вернуться к историям',
    'story.endingHappy': 'Конец истории!',
    'story.endingAlt': 'Другой конец...',
    'story.listenStory': 'Слушать историю',
    'story.stopListening': 'Остановить',
    'story.downloadColoring': 'Раскраска с динозаврами',
    'story.whatToDo': 'Что ты хочешь сделать?',
    'story.restart': 'Начать историю сначала',
    'story.otherStories': 'Другие истории',
    'start.enterName': 'Введи своё имя',
    'start.yourName': 'Твоё имя',
    'start.namePlaceholder': 'Напр: Эмма, Лукас...',
    'start.nameHint': 'Твоё имя появится в истории!',
    'start.chooseGender': 'Выбери пол',
    'start.genderMasculine': 'Мужской',
    'start.genderFeminine': 'Женский',
    'start.genderNeutral': 'Нейтральный',
    'start.genderHint': 'Это адаптирует некоторые слова в истории.',
    'start.beginAdventure': 'Начинаем приключение!',
    'start.back': 'Назад',
    'footer.tagline': 'Волшебные истории для весёлого обучения',
    'footer.rights': 'Все права защищены.',
    'footer.why': 'Почему этот сайт?',
    'footer.whyText1': 'Я фанат ролевых игр, информатики и скоро стану папой.',
    'footer.whyText2': 'Я исходил из простого наблюдения: школьная программа существует, но способ её изучения подходит не всем детям.',
    'footer.whyText3': 'Поэтому я создал образовательный сайт в виде книги-игры. Ребёнок становится главным героем, делает выбор, продвигается по истории... и учит школьную программу, не замечая этого.',
    'footer.whyText4': 'Всё начинается с подготовительного класса с ясной амбицией: построить каждый уровень, класс за классом. Сегодня уже есть несколько историй, пока исследовательских, но отзывы очень положительные.',
    'footer.whyText5': 'Цель теперь: обогатить вселенную, добавить больше приключений и предложить более увлекательную альтернативу, лучше адаптированную к разнообразию детей.',
    'footer.contact': 'Есть идея? Вопрос?',
    'footer.contactText': 'Свяжитесь со мной в',
    'subjects.subtitle': 'Выбери предмет, чтобы открыть увлекательные истории!',
    'subjects.lecture.name': 'Французский',
    'subjects.lecture': 'Интерактивные истории для обучения чтению',
    'subjects.mathematiques.name': 'Математика',
    'subjects.mathematiques': 'Приключения для изучения чисел',
    'subjects.histoire.name': 'История',
    'subjects.histoire': 'Путешествия во времени и открытия',
    'subjects.geographie.name': 'География',
    'subjects.geographie': 'Исследования мира',
    'subjects.sciences.name': 'Наука',
    'subjects.sciences': 'Эксперименты и научные открытия',
    'subjects.langues.name': 'Языки',
    'subjects.langues': 'Изучение английского с удовольствием',
    'stories.notFound': 'История не найдена',
    'stories.notFoundDesc': 'Эта история не существует или была удалена.',
    'start.customize': 'Настрой своё приключение',
    'start.ready': 'Готов',
    'start.begin': 'Поехали!',
    'nav.backToGrades': 'Вернуться к уровням',
    'grades.title': 'В каком ты классе?',
    'grades.subtitle': 'Выбери класс для подходящих приключений!',
    'grades.cp.fullName': 'Подготовительный класс',
    'grades.cp.description': 'Первые читательские приключения',
    'grades.ce1.fullName': '1 класс',
    'grades.ce1.description': 'Открытия и исследования',
    'grades.ce2.fullName': '2 класс',
    'grades.ce2.description': 'Путешествия и науки',
    'grades.cm1.fullName': '3 класс',
    'grades.cm1.description': 'История и открытия',
    'grades.cm2.fullName': '4 класс',
    'grades.cm2.description': 'Продвинутые приключения',
    'myStories.title': 'Мои истории',
    'myStories.greeting': 'Добро пожаловать {name}!',
    'myStories.createProfile': 'Создать профиль',
    'myStories.createProfileDesc': 'Создай профиль, чтобы сохранить прогресс!',
    'myStories.completed': 'Завершённые истории',
    'myStories.endings': 'Открытые концовки',
    'myStories.inProgress': 'В процессе',
    'myStories.continueReading': 'Продолжить чтение',
    'myStories.toDiscover': 'К открытию',
    'myStories.completedStories': 'Завершённые истории',
    'myStories.noCompleted': 'Ты ещё не закончил ни одной истории. Начни приключение!',
    'myStories.discover': 'Открыть истории',
    'myStories.replay': 'Переиграть',
    'stories.continue': 'Продолжить',
    'stories.title': 'Выбери своё приключение!',
    'stories.readStory': 'Читать историю',
    'stories.restart': 'Начать историю сначала',
    'stories.otherStories': 'Другие истории',
    'stories.pageNotFound': 'Страница не найдена',
    'stories.pageNotFoundDesc': 'Эта страница не существует.',
    'reader.endingHappy': 'Конец истории!',
    'reader.endingAlt': 'Другой конец...',
    'reader.stop': 'Остановить',
    'reader.listen': 'Слушать историю',
    'reader.coloringDownload': 'Раскраска с динозаврами',
    'reader.whatToDo': 'Что ты хочешь сделать?',
    'card.completed': 'Завершено',
    'card.inProgress': 'В процессе',
    'card.letsGo': 'Поехали!',
    'card.comingSoon': 'Скоро',
    'card.share': 'Поделиться:',
    'card.shareThis': 'Поделиться этим сайтом',
    'account.whyCreate': 'Зачем создавать аккаунт?',
    'account.profileDesc': 'Создайте профиль для каждого ребёнка с аватаром и именем для более захватывающих историй.',
    'account.historyDesc': 'Легко находите текущие чтения и продолжайте с того места, где остановились.',
    'account.trackingDesc': 'Смотрите, какие истории прочитаны и какие ещё предстоит открыть.',
    'account.benefitText': 'Создание аккаунта гарантирует простое отслеживание и персонализированный опыт.',
    'account.createFree': 'Создать бесплатный аккаунт',
    'nav.leaveStory': 'Выйти из истории',
    'common.loading': 'Загрузка...',
    'common.completed': 'Завершено',
    'common.ends': 'концовок',
    'common.end': 'концовка',
    'general.loading': 'Загрузка...',
    'general.error': 'Ошибка',
    'general.success': 'Успех',
    'general.cancel': 'Отмена',
    'general.save': 'Сохранить',
    'general.delete': 'Удалить',
    'general.edit': 'Редактировать',
    'general.close': 'Закрыть',
    'editor.adminMode': 'Режим редактирования администратора',
    'editor.placeholder': 'Текст страницы...',
    'editor.textUpdated': 'Текст обновлён для всех пользователей',
    'editor.saveError': 'Ошибка при сохранении',
    'editor.textRestored': 'Текст восстановлен до оригинала',
    'editor.restoreError': 'Ошибка при восстановлении',
    'editor.restoreOriginal': 'Восстановить оригинал',
    'editor.modified': 'изменено',

    // Inventory
    'inventory.title': 'Инвентарь',
    'inventory.newItem': 'Новый предмет!',
  },
  es: {
    'nav.back': 'Volver',
    'nav.backToSubjects': 'Volver a las materias',
    'nav.backToStories': 'Volver a las historias',
    'nav.quitStory': 'Salir de la historia',
    'nav.home': 'Inicio',
    'auth.login': 'Iniciar sesión',
    'auth.logout': 'Cerrar sesión',
    'auth.register': 'Crear cuenta',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.firstName': 'Nombre',
    'auth.loginTitle': 'Iniciar sesión',
    'auth.registerTitle': 'Crear cuenta',
    'auth.loginSubtitle': '¡Encuentra tus historias y tu progreso!',
    'auth.registerSubtitle': '¡Únete a los héroes de la clase!',
    'auth.loginSuccess': '¡Inicio de sesión exitoso!',
    'auth.loginSuccessDesc': '¡Bienvenido de nuevo!',
    'auth.welcomeBack': '¡Bienvenido de nuevo!',
    'auth.loginError': 'Error de inicio de sesión',
    'auth.invalidCredentials': 'Correo o contraseña incorrectos.',
    'auth.error': 'Error',
    'auth.genericError': 'Ocurrió un error. Inténtalo más tarde.',
    'auth.submit': 'Iniciar sesión',
    'auth.loginButton': 'Iniciar sesión',
    'auth.registerButton': 'Crear mi cuenta',
    'auth.createAccount': 'Crear mi cuenta',
    'auth.passwordMismatch': 'Las contraseñas no coinciden.',
    'auth.accountExists': 'Esta cuenta ya existe.',
    'auth.registerSuccess': '¡Cuenta creada!',
    'auth.registerSuccessDesc': '¡Bienvenido entre los héroes!',
    'menu.myAccount': 'Mi cuenta',
    'menu.changeAvatar': 'Cambiar avatar',
    'menu.myStories': 'Mis historias',
    'menu.admin': 'Administración',
    'menu.seeYou': '¡Hasta pronto!',
    'menu.loggedOut': 'Has cerrado sesión.',
    'menu.adventurer': 'Aventurero',
    'avatar.chooseTitle': 'Elige tu avatar',
    'avatar.chooseSubtitle': '¡Selecciona el personaje que se parezca a ti!',
    'avatar.cancel': 'Cancelar',
    'avatar.save': 'Guardar',
    'avatar.saving': 'Guardando...',
    'avatar.changed': '¡Avatar cambiado!',
    'avatar.changedDesc': '¡Tu nuevo avatar se ve genial!',
    'avatar.error': 'No se pudo cambiar el avatar',
    'stories.chooseAdventure': '¡Elige tu aventura!',
    'stories.saveProgress': 'Guardar mi progreso',
    'stories.loading': 'Cargando historias...',
    'stories.noStories': 'No hay historias disponibles para esta materia en',
    'stories.chooseOther': 'Elegir otra materia',
    'story.pageNotFound': 'Página no encontrada',
    'story.pageNotFoundDesc': 'Esta página no existe.',
    'story.backToStories': 'Volver a las historias',
    'story.endingHappy': '¡Fin de la historia!',
    'story.endingAlt': 'Otro final...',
    'story.listenStory': 'Escuchar la historia',
    'story.stopListening': 'Detener',
    'story.downloadColoring': 'Colorear dinosaurios',
    'story.whatToDo': '¿Qué quieres hacer?',
    'story.restart': 'Reiniciar esta historia',
    'story.otherStories': 'Otras historias',
    'start.enterName': 'Ingresa tu nombre',
    'start.yourName': 'Tu nombre',
    'start.namePlaceholder': 'Ej: Emma, Lucas...',
    'start.nameHint': '¡Tu nombre aparecerá en la historia!',
    'start.chooseGender': 'Elige tu género',
    'start.genderMasculine': 'Masculino',
    'start.genderFeminine': 'Femenino',
    'start.genderNeutral': 'Neutral',
    'start.genderHint': 'Esto adaptará algunas palabras de la historia.',
    'start.beginAdventure': '¡Comienza la aventura!',
    'start.back': 'Volver',
    'footer.tagline': 'Historias mágicas para aprender jugando',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.why': '¿Por qué este sitio?',
    'footer.whyText1': 'Soy fan de los juegos de rol, la informática y pronto seré papá.',
    'footer.whyText2': 'Partí de una observación simple: el programa escolar existe, pero la forma de aprenderlo no se adapta a todos los niños.',
    'footer.whyText3': 'Por eso creé un sitio educativo en forma de libro-juego. El niño se convierte en el personaje principal, toma decisiones, avanza en una historia... y aprende el programa sin darse cuenta.',
    'footer.whyText4': 'Comienza en preescolar, con una ambición clara: construir cada nivel, clase por clase. Hoy ya hay varias historias, aún exploratorias, pero los comentarios son muy positivos.',
    'footer.whyText5': 'El objetivo ahora: enriquecer el universo, añadir más aventuras y ofrecer una alternativa más atractiva y adaptada a la diversidad de los niños.',
    'footer.contact': '¿Tienes una idea? ¿Una pregunta?',
    'footer.contactText': 'No dudes en contactarme en',
    'subjects.subtitle': '¡Elige una materia para descubrir historias emocionantes!',
    'subjects.lecture.name': 'Francés',
    'subjects.lecture': 'Historias interactivas para aprender a leer',
    'subjects.mathematiques.name': 'Matemáticas',
    'subjects.mathematiques': 'Aventuras para descubrir los números',
    'subjects.histoire.name': 'Historia',
    'subjects.histoire': 'Viajes en el tiempo y descubrimientos',
    'subjects.geographie.name': 'Geografía',
    'subjects.geographie': 'Exploraciones del mundo entero',
    'subjects.sciences.name': 'Ciencias',
    'subjects.sciences': 'Experimentos y descubrimientos científicos',
    'subjects.langues.name': 'Idiomas',
    'subjects.langues': 'Aprender inglés divirtiéndose',
    'stories.notFound': 'Historia no encontrada',
    'stories.notFoundDesc': 'Esta historia no existe o ha sido eliminada.',
    'start.customize': 'Personaliza tu aventura',
    'start.ready': 'Listo',
    'start.begin': '¡Vamos!',
    'nav.backToGrades': 'Volver a los niveles',
    'grades.title': '¿En qué grado estás?',
    'grades.subtitle': '¡Elige tu clase para descubrir aventuras adaptadas!',
    'grades.cp.fullName': 'Preescolar',
    'grades.cp.description': 'Primeras aventuras de lectura',
    'grades.ce1.fullName': '1er Grado',
    'grades.ce1.description': 'Descubrimientos y exploraciones',
    'grades.ce2.fullName': '2do Grado',
    'grades.ce2.description': 'Viajes y ciencias',
    'grades.cm1.fullName': '3er Grado',
    'grades.cm1.description': 'Historia y descubrimientos',
    'grades.cm2.fullName': '4to Grado',
    'grades.cm2.description': 'Aventuras avanzadas',
    'myStories.title': 'Mis historias',
    'myStories.greeting': '¡Bienvenido {name}!',
    'myStories.createProfile': 'Crear perfil',
    'myStories.createProfileDesc': '¡Crea un perfil para guardar tu progreso!',
    'myStories.completed': 'Historias completadas',
    'myStories.endings': 'Finales descubiertos',
    'myStories.inProgress': 'En progreso',
    'myStories.continueReading': 'Continuar leyendo',
    'myStories.toDiscover': 'Por descubrir',
    'myStories.completedStories': 'Historias completadas',
    'myStories.noCompleted': '¡Aún no has terminado ninguna historia. Comienza una aventura!',
    'myStories.discover': 'Descubrir historias',
    'myStories.replay': 'Volver a jugar',
    'stories.continue': 'Continuar',
    'stories.title': '¡Elige tu aventura!',
    'stories.readStory': 'Leer la historia',
    'stories.restart': 'Reiniciar esta historia',
    'stories.otherStories': 'Otras historias',
    'stories.pageNotFound': 'Página no encontrada',
    'stories.pageNotFoundDesc': 'Esta página no existe.',
    'reader.endingHappy': '¡Fin de la historia!',
    'reader.endingAlt': 'Otro final...',
    'reader.stop': 'Detener',
    'reader.listen': 'Escuchar la historia',
    'reader.coloringDownload': 'Colorear dinosaurios',
    'reader.whatToDo': '¿Qué quieres hacer?',
    'card.completed': 'Completada',
    'card.inProgress': 'En progreso',
    'card.letsGo': '¡Vamos!',
    'card.comingSoon': 'Próximamente',
    'card.share': 'Compartir:',
    'card.shareThis': 'Compartir este sitio',
    'account.whyCreate': '¿Por qué crear una cuenta?',
    'account.profileDesc': 'Crea un perfil para cada niño con su avatar y nombre para historias más inmersivas.',
    'account.historyDesc': 'Encuentra fácilmente las lecturas en curso y continúa donde lo dejaste.',
    'account.trackingDesc': 'Mira qué historias se han leído y cuáles quedan por descubrir.',
    'account.benefitText': 'Crear una cuenta garantiza un seguimiento simple y una experiencia personalizada.',
    'account.createFree': 'Crear cuenta gratuita',
    'nav.leaveStory': 'Salir de la historia',
    'common.loading': 'Cargando...',
    'common.completed': 'Completado',
    'common.ends': 'finales',
    'common.end': 'final',
    'general.loading': 'Cargando...',
    'general.error': 'Error',
    'general.success': 'Éxito',
    'general.cancel': 'Cancelar',
    'general.save': 'Guardar',
    'general.delete': 'Eliminar',
    'general.edit': 'Editar',
    'general.close': 'Cerrar',
    'editor.adminMode': 'Modo de edición admin',
    'editor.placeholder': 'Texto de la página...',
    'editor.textUpdated': 'Texto actualizado para todos los usuarios',
    'editor.saveError': 'Error al guardar',
    'editor.textRestored': 'Texto restaurado a la versión original',
    'editor.restoreError': 'Error al restaurar',
    'editor.restoreOriginal': 'Restaurar original',
    'editor.modified': 'modificado',

    // Inventory
    'inventory.title': 'Inventario',
    'inventory.newItem': '¡Nuevo objeto!',
  },
  zh: {
    'nav.back': '返回',
    'nav.backToSubjects': '返回科目',
    'nav.backToStories': '返回故事',
    'nav.quitStory': '退出故事',
    'nav.home': '首页',
    'auth.login': '登录',
    'auth.logout': '退出登录',
    'auth.register': '创建账户',
    'auth.noAccount': '还没有账户？',
    'auth.hasAccount': '已有账户？',
    'auth.email': '电子邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.firstName': '名字',
    'auth.loginTitle': '登录',
    'auth.registerTitle': '创建账户',
    'auth.loginSubtitle': '找回你的故事和进度！',
    'auth.registerSubtitle': '加入班级英雄！',
    'auth.loginSuccess': '登录成功！',
    'auth.loginSuccessDesc': '欢迎回来！',
    'auth.welcomeBack': '欢迎回来！',
    'auth.loginError': '登录错误',
    'auth.invalidCredentials': '邮箱或密码错误。',
    'auth.error': '错误',
    'auth.genericError': '发生错误，请稍后重试。',
    'auth.submit': '登录',
    'auth.loginButton': '登录',
    'auth.registerButton': '创建账户',
    'auth.createAccount': '创建账户',
    'auth.passwordMismatch': '密码不匹配。',
    'auth.accountExists': '此账户已存在。',
    'auth.registerSuccess': '账户已创建！',
    'auth.registerSuccessDesc': '欢迎加入英雄！',
    'menu.myAccount': '我的账户',
    'menu.changeAvatar': '更换头像',
    'menu.myStories': '我的故事',
    'menu.admin': '管理',
    'menu.seeYou': '再见！',
    'menu.loggedOut': '您已退出登录。',
    'menu.adventurer': '冒险家',
    'avatar.chooseTitle': '选择你的头像',
    'avatar.chooseSubtitle': '选择像你的角色！',
    'avatar.cancel': '取消',
    'avatar.save': '保存',
    'avatar.saving': '保存中...',
    'avatar.changed': '头像已更改！',
    'avatar.changedDesc': '你的新头像看起来很棒！',
    'avatar.error': '无法更改头像',
    'stories.chooseAdventure': '选择你的冒险！',
    'stories.saveProgress': '保存进度',
    'stories.loading': '加载故事中...',
    'stories.noStories': '该科目没有可用的故事',
    'stories.chooseOther': '选择其他科目',
    'story.pageNotFound': '页面未找到',
    'story.pageNotFoundDesc': '此页面不存在。',
    'story.backToStories': '返回故事',
    'story.endingHappy': '故事结束！',
    'story.endingAlt': '另一个结局...',
    'story.listenStory': '听故事',
    'story.stopListening': '停止',
    'story.downloadColoring': '恐龙涂色',
    'story.whatToDo': '你想做什么？',
    'story.restart': '重新开始这个故事',
    'story.otherStories': '其他故事',
    'start.enterName': '输入你的名字',
    'start.yourName': '你的名字',
    'start.namePlaceholder': '例如：艾玛、卢卡斯...',
    'start.nameHint': '你的名字会出现在故事中！',
    'start.chooseGender': '选择你的性别',
    'start.genderMasculine': '男性',
    'start.genderFeminine': '女性',
    'start.genderNeutral': '中性',
    'start.genderHint': '这将调整故事中的某些词语。',
    'start.beginAdventure': '开始冒险吧！',
    'start.back': '返回',
    'footer.tagline': '在欢乐中学习的魔法故事',
    'footer.rights': '版权所有。',
    'footer.why': '为什么有这个网站？',
    'footer.whyText1': '我是角色扮演游戏和计算机的爱好者，很快就要当爸爸了。',
    'footer.whyText2': '我从一个简单的观察出发：学校课程是存在的，但学习方式并不适合所有孩子。',
    'footer.whyText3': '所以我创建了一个游戏书形式的教育网站。孩子成为主角，做出选择，推进故事……在不知不觉中学习课程。',
    'footer.whyText4': '从学前班开始，有一个明确的目标：一个年级一个年级地构建每个级别。今天已经有几个故事了，还在探索中，但反馈非常积极。',
    'footer.whyText5': '现在的目标：丰富这个世界，添加更多冒险，提供一个更吸引人、更适合儿童多样性的替代方案。',
    'footer.contact': '有想法？有问题？',
    'footer.contactText': '请通过以下方式联系我',
    'subjects.subtitle': '选择一个科目来发现精彩的故事！',
    'subjects.lecture.name': '法语',
    'subjects.lecture': '互动故事学习阅读',
    'subjects.mathematiques.name': '数学',
    'subjects.mathematiques': '探索数字的冒险',
    'subjects.histoire.name': '历史',
    'subjects.histoire': '时间旅行和发现',
    'subjects.geographie.name': '地理',
    'subjects.geographie': '探索整个世界',
    'subjects.sciences.name': '科学',
    'subjects.sciences': '实验和科学发现',
    'subjects.langues.name': '语言',
    'subjects.langues': '快乐学英语',
    'stories.notFound': '故事未找到',
    'stories.notFoundDesc': '这个故事不存在或已被删除。',
    'start.customize': '定制你的冒险',
    'start.ready': '准备好了',
    'start.begin': '出发！',
    'nav.backToGrades': '返回年级',
    'grades.title': '你在几年级？',
    'grades.subtitle': '选择你的年级来发现适合的冒险！',
    'grades.cp.fullName': '学前班',
    'grades.cp.description': '第一次阅读冒险',
    'grades.ce1.fullName': '一年级',
    'grades.ce1.description': '发现与探索',
    'grades.ce2.fullName': '二年级',
    'grades.ce2.description': '旅行与科学',
    'grades.cm1.fullName': '三年级',
    'grades.cm1.description': '历史与发现',
    'grades.cm2.fullName': '四年级',
    'grades.cm2.description': '高级冒险',
    'myStories.title': '我的故事',
    'myStories.greeting': '欢迎 {name}！',
    'myStories.createProfile': '创建档案',
    'myStories.createProfileDesc': '创建档案以保存你的进度！',
    'myStories.completed': '已完成的故事',
    'myStories.endings': '发现的结局',
    'myStories.inProgress': '进行中',
    'myStories.continueReading': '继续阅读',
    'myStories.toDiscover': '待发现',
    'myStories.completedStories': '已完成的故事',
    'myStories.noCompleted': '你还没有完成任何故事。开始一段冒险吧！',
    'myStories.discover': '发现故事',
    'myStories.replay': '重玩',
    'stories.continue': '继续',
    'stories.title': '选择你的冒险！',
    'stories.readStory': '阅读故事',
    'stories.restart': '重新开始这个故事',
    'stories.otherStories': '其他故事',
    'stories.pageNotFound': '页面未找到',
    'stories.pageNotFoundDesc': '此页面不存在。',
    'reader.endingHappy': '故事结束！',
    'reader.endingAlt': '另一个结局...',
    'reader.stop': '停止',
    'reader.listen': '听故事',
    'reader.coloringDownload': '恐龙涂色',
    'reader.whatToDo': '你想做什么？',
    'card.completed': '已完成',
    'card.inProgress': '进行中',
    'card.letsGo': '出发！',
    'card.comingSoon': '即将推出',
    'card.share': '分享：',
    'card.shareThis': '分享这个网站',
    'account.whyCreate': '为什么创建账户？',
    'account.profileDesc': '为每个孩子创建一个包含头像和名字的档案，让故事更加身临其境。',
    'account.historyDesc': '轻松找到正在阅读的内容，从上次停止的地方继续。',
    'account.trackingDesc': '查看已阅读的故事和待发现的故事。',
    'account.benefitText': '创建账户可确保简单跟踪和个性化体验。',
    'account.createFree': '创建免费账户',
    'nav.leaveStory': '退出故事',
    'common.loading': '加载中...',
    'common.completed': '已完成',
    'common.ends': '个结局',
    'common.end': '个结局',
    'general.loading': '加载中...',
    'general.error': '错误',
    'general.success': '成功',
    'general.cancel': '取消',
    'general.save': '保存',
    'general.delete': '删除',
    'general.edit': '编辑',
    'general.close': '关闭',
    'editor.adminMode': '管理员编辑模式',
    'editor.placeholder': '页面文本...',
    'editor.textUpdated': '已为所有用户更新文本',
    'editor.saveError': '保存时出错',
    'editor.textRestored': '文本已恢复为原始版本',
    'editor.restoreError': '恢复时出错',
    'editor.restoreOriginal': '恢复原始',
    'editor.modified': '已修改',

    // Inventory
    'inventory.title': '物品栏',
    'inventory.newItem': '新物品！',
  },
  'pt-br': {
    'nav.back': 'Voltar',
    'nav.backToSubjects': 'Voltar às matérias',
    'nav.backToStories': 'Voltar às histórias',
    'nav.quitStory': 'Sair da história',
    'nav.home': 'Início',
    'auth.login': 'Entrar',
    'auth.logout': 'Sair',
    'auth.register': 'Criar conta',
    'auth.noAccount': 'Não tem conta?',
    'auth.hasAccount': 'Já tem conta?',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.confirmPassword': 'Confirmar senha',
    'auth.firstName': 'Nome',
    'auth.loginTitle': 'Entrar',
    'auth.registerTitle': 'Criar conta',
    'auth.loginSubtitle': 'Encontre suas histórias e progresso!',
    'auth.registerSubtitle': 'Junte-se aos heróis da classe!',
    'auth.loginSuccess': 'Login bem-sucedido!',
    'auth.loginSuccessDesc': 'Bem-vindo de volta!',
    'auth.welcomeBack': 'Bem-vindo de volta!',
    'auth.loginError': 'Erro de login',
    'auth.invalidCredentials': 'E-mail ou senha incorretos.',
    'auth.error': 'Erro',
    'auth.genericError': 'Ocorreu um erro. Tente novamente mais tarde.',
    'auth.submit': 'Entrar',
    'auth.loginButton': 'Entrar',
    'auth.registerButton': 'Criar minha conta',
    'auth.createAccount': 'Criar minha conta',
    'auth.passwordMismatch': 'As senhas não coincidem.',
    'auth.accountExists': 'Esta conta já existe.',
    'auth.registerSuccess': 'Conta criada!',
    'auth.registerSuccessDesc': 'Bem-vindo aos heróis!',
    'menu.myAccount': 'Minha conta',
    'menu.changeAvatar': 'Mudar avatar',
    'menu.myStories': 'Minhas histórias',
    'menu.admin': 'Administração',
    'menu.seeYou': 'Até logo!',
    'menu.loggedOut': 'Você saiu da conta.',
    'menu.adventurer': 'Aventureiro',
    'avatar.chooseTitle': 'Escolha seu avatar',
    'avatar.chooseSubtitle': 'Selecione o personagem que se parece com você!',
    'avatar.cancel': 'Cancelar',
    'avatar.save': 'Salvar',
    'avatar.saving': 'Salvando...',
    'avatar.changed': 'Avatar alterado!',
    'avatar.changedDesc': 'Seu novo avatar está incrível!',
    'avatar.error': 'Não foi possível alterar o avatar',
    'stories.chooseAdventure': 'Escolha sua aventura!',
    'stories.saveProgress': 'Salvar meu progresso',
    'stories.loading': 'Carregando histórias...',
    'stories.noStories': 'Nenhuma história disponível para esta matéria em',
    'stories.chooseOther': 'Escolher outra matéria',
    'story.pageNotFound': 'Página não encontrada',
    'story.pageNotFoundDesc': 'Esta página não existe.',
    'story.backToStories': 'Voltar às histórias',
    'story.endingHappy': 'Fim da história!',
    'story.endingAlt': 'Outro final...',
    'story.listenStory': 'Ouvir a história',
    'story.stopListening': 'Parar',
    'story.downloadColoring': 'Colorir dinossauros',
    'story.whatToDo': 'O que você quer fazer?',
    'story.restart': 'Recomeçar esta história',
    'story.otherStories': 'Outras histórias',
    'start.enterName': 'Digite seu nome',
    'start.yourName': 'Seu nome',
    'start.namePlaceholder': 'Ex: Emma, Lucas...',
    'start.nameHint': 'Seu nome aparecerá na história!',
    'start.chooseGender': 'Escolha seu gênero',
    'start.genderMasculine': 'Masculino',
    'start.genderFeminine': 'Feminino',
    'start.genderNeutral': 'Neutro',
    'start.genderHint': 'Isso adaptará algumas palavras da história.',
    'start.beginAdventure': 'Vamos começar a aventura!',
    'start.back': 'Voltar',
    'footer.tagline': 'Histórias mágicas para aprender brincando',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.why': 'Por que este site?',
    'footer.whyText1': 'Sou fã de RPG, informática e em breve serei pai.',
    'footer.whyText2': 'Parti de uma observação simples: o currículo escolar existe, mas a forma de aprender não se adapta a todas as crianças.',
    'footer.whyText3': 'Por isso criei um site educativo no formato de livro-jogo. A criança se torna o personagem principal, faz escolhas, avança na história... e aprende o currículo sem perceber.',
    'footer.whyText4': 'Começa na pré-escola, com uma ambição clara: construir cada nível, série por série. Hoje já existem várias histórias, ainda exploratórias, mas os retornos são muito positivos.',
    'footer.whyText5': 'O objetivo agora: enriquecer o universo, adicionar mais aventuras e oferecer uma alternativa mais envolvente e adaptada à diversidade das crianças.',
    'footer.contact': 'Tem uma ideia? Uma pergunta?',
    'footer.contactText': 'Fique à vontade para me contatar no',
    'subjects.subtitle': 'Escolha uma matéria para descobrir histórias emocionantes!',
    'subjects.lecture.name': 'Francês',
    'subjects.lecture': 'Histórias interativas para aprender a ler',
    'subjects.mathematiques.name': 'Matemática',
    'subjects.mathematiques': 'Aventuras para descobrir os números',
    'subjects.histoire.name': 'História',
    'subjects.histoire': 'Viagens no tempo e descobertas',
    'subjects.geographie.name': 'Geografia',
    'subjects.geographie': 'Explorações do mundo inteiro',
    'subjects.sciences.name': 'Ciências',
    'subjects.sciences': 'Experimentos e descobertas científicas',
    'subjects.langues.name': 'Idiomas',
    'subjects.langues': 'Aprender inglês brincando',
    'stories.notFound': 'História não encontrada',
    'stories.notFoundDesc': 'Esta história não existe ou foi excluída.',
    'start.customize': 'Personalize sua aventura',
    'start.ready': 'Pronto',
    'start.begin': 'Vamos lá!',
    'nav.backToGrades': 'Voltar às séries',
    'grades.title': 'Em que série você está?',
    'grades.subtitle': 'Escolha sua série para descobrir aventuras adaptadas!',
    'grades.cp.fullName': 'Pré-escola',
    'grades.cp.description': 'Primeiras aventuras de leitura',
    'grades.ce1.fullName': '1ª Série',
    'grades.ce1.description': 'Descobertas e explorações',
    'grades.ce2.fullName': '2ª Série',
    'grades.ce2.description': 'Viagens e ciências',
    'grades.cm1.fullName': '3ª Série',
    'grades.cm1.description': 'História e descobertas',
    'grades.cm2.fullName': '4ª Série',
    'grades.cm2.description': 'Aventuras avançadas',
    'myStories.title': 'Minhas histórias',
    'myStories.greeting': 'Bem-vindo {name}!',
    'myStories.createProfile': 'Criar perfil',
    'myStories.createProfileDesc': 'Crie um perfil para salvar seu progresso!',
    'myStories.completed': 'Histórias completadas',
    'myStories.endings': 'Finais descobertos',
    'myStories.inProgress': 'Em andamento',
    'myStories.continueReading': 'Continuar lendo',
    'myStories.toDiscover': 'Para descobrir',
    'myStories.completedStories': 'Histórias completadas',
    'myStories.noCompleted': 'Você ainda não terminou nenhuma história. Comece uma aventura!',
    'myStories.discover': 'Descobrir histórias',
    'myStories.replay': 'Jogar novamente',
    'stories.continue': 'Continuar',
    'stories.title': 'Escolha sua aventura!',
    'stories.readStory': 'Ler a história',
    'stories.restart': 'Recomeçar esta história',
    'stories.otherStories': 'Outras histórias',
    'stories.pageNotFound': 'Página não encontrada',
    'stories.pageNotFoundDesc': 'Esta página não existe.',
    'reader.endingHappy': 'Fim da história!',
    'reader.endingAlt': 'Outro final...',
    'reader.stop': 'Parar',
    'reader.listen': 'Ouvir a história',
    'reader.coloringDownload': 'Colorir dinossauros',
    'reader.whatToDo': 'O que você quer fazer?',
    'card.completed': 'Completada',
    'card.inProgress': 'Em andamento',
    'card.letsGo': 'Vamos lá!',
    'card.comingSoon': 'Em breve',
    'card.share': 'Compartilhar:',
    'card.shareThis': 'Compartilhar este site',
    'account.whyCreate': 'Por que criar uma conta?',
    'account.profileDesc': 'Crie um perfil para cada criança com avatar e nome para histórias mais imersivas.',
    'account.historyDesc': 'Encontre facilmente leituras em andamento e continue de onde parou.',
    'account.trackingDesc': 'Veja quais histórias foram lidas e quais ainda faltam descobrir.',
    'account.benefitText': 'Criar uma conta garante acompanhamento simples e experiência personalizada.',
    'account.createFree': 'Criar conta gratuita',
    'nav.leaveStory': 'Sair da história',
    'common.loading': 'Carregando...',
    'common.completed': 'Completado',
    'common.ends': 'finais',
    'common.end': 'final',
    'general.loading': 'Carregando...',
    'general.error': 'Erro',
    'general.success': 'Sucesso',
    'general.cancel': 'Cancelar',
    'general.save': 'Salvar',
    'general.delete': 'Excluir',
    'general.edit': 'Editar',
    'general.close': 'Fechar',
    'editor.adminMode': 'Modo de edição admin',
    'editor.placeholder': 'Texto da página...',
    'editor.textUpdated': 'Texto atualizado para todos os usuários',
    'editor.saveError': 'Erro ao salvar',
    'editor.textRestored': 'Texto restaurado para versão original',
    'editor.restoreError': 'Erro ao restaurar',
    'editor.restoreOriginal': 'Restaurar original',
    'editor.modified': 'modificado',

    // Inventory
    'inventory.title': 'Inventário',
    'inventory.newItem': 'Novo item!',
  },
};

// Translation cache with localStorage persistence
const CACHE_KEY = 'translation-cache';
const MAX_CACHE_SIZE = 500;

// Load cache from localStorage on startup
const loadCacheFromStorage = (): Map<string, string> => {
  try {
    const stored = localStorage.getItem(CACHE_KEY);
    if (stored) {
      const entries = JSON.parse(stored) as [string, string][];
      return new Map(entries);
    }
  } catch (e) {
    console.error('Failed to load translation cache:', e);
  }
  return new Map();
};

// Save cache to localStorage
const saveCacheToStorage = (cache: Map<string, string>) => {
  try {
    // Limit cache size
    const entries = Array.from(cache.entries()).slice(-MAX_CACHE_SIZE);
    localStorage.setItem(CACHE_KEY, JSON.stringify(entries));
  } catch (e) {
    console.error('Failed to save translation cache:', e);
  }
};

const translationCache = loadCacheFromStorage();
const pendingTranslations = new Map<string, Promise<string>>();

// Export for useTranslatedString to check cache synchronously
export const getFromTranslationCache = (cacheKey: string): string | undefined => {
  return translationCache.get(cacheKey);
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('preferred-language');
    return (saved as Language) || 'fr';
  });
  const [isTranslating, setIsTranslating] = useState(false);

  useEffect(() => {
    localStorage.setItem('preferred-language', language);
    document.documentElement.lang = language === 'pt-br' ? 'pt-BR' : language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.fr[key] || key;
  };

  const translateText = async (text: string, targetLang?: Language): Promise<string> => {
    const lang = targetLang || language;
    if (lang === 'fr') return text; // No translation needed for French
    if (!text || text.trim() === '') return text;

    // Check cache first
    const cacheKey = `${lang}:${text}`;
    if (translationCache.has(cacheKey)) {
      return translationCache.get(cacheKey)!;
    }

    // Check if already pending (deduplication)
    if (pendingTranslations.has(cacheKey)) {
      return pendingTranslations.get(cacheKey)!;
    }

    // Create the translation promise with timeout
    const translationPromise = (async (): Promise<string> => {
      setIsTranslating(true);
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 10000); // 10s timeout

      try {
        const response = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/translate`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
          },
          body: JSON.stringify({ text, targetLanguage: lang }),
          signal: controller.signal,
        });

        clearTimeout(timeoutId);

        if (!response.ok) {
          console.error('Translation error:', response.status);
          // On 429/402 errors, just return original text without caching to allow retry later
          return text;
        }

        const data = await response.json();
        const translatedText = data.translatedText || text;
        
        // Cache successful translation (memory + localStorage)
        translationCache.set(cacheKey, translatedText);
        saveCacheToStorage(translationCache);
        return translatedText;
      } catch (error) {
        clearTimeout(timeoutId);
        console.error('Translation failed:', error);
        return text; // Return original on error
      } finally {
        setIsTranslating(false);
        pendingTranslations.delete(cacheKey);
      }
    })();

    pendingTranslations.set(cacheKey, translationPromise);
    return translationPromise;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translateText, isTranslating }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
